title: Default Page
preset: page
fields:
  introtext:
    label: Intro Text
    type: textarea
    size: small
  WhatTitle:
    label: What is a service blueprint
    type: textarea
    size: small
  WhatText:
    label: What is - text
    type: textarea
    size: small
  WhatTitleTwo:
    label: What is service design
    type: textarea
    size: small
  WhatTextTwo:
    label: What is - text
    type: textarea
    size: small
  WhenText:
    label: When text
    type: textarea
    size: small
  HowTitle:
    label: How title
    type: textarea
    size: small
  HowText:
    label: How text
    type: textarea
    size: small
  TitleFirst:
    label: Title first step
    type: textarea
    size: small
  TextFirst:
    label: How text
    type: textarea
    size: small
  TitleSecond:
    label: Title second step
    type: textarea
    size: small
  TextSecond:
    label: How text
    type: textarea
    size: small
  TitleThird:
    label: Title third step
    type: textarea
    size: small
  TextThird:
    label: How text
    type: textarea
    size: small
  TitleFourth:
    label: Title fourth step
    type: textarea
    size: small
  TextFourth:
    label: How text
    type: textarea
    size: small
  TitleFifth:
    label: Tilte fifth step
    type: textarea
    size: small
  TextFifth:
    label: How text
    type: textarea
    size: small

  TitleImplement:
    label: HowTitle
    type: textarea
    size: small
  TextImplement:
    label: Implementtekstvlak
    type: textarea
    size: small 

  BronnenTitle:
    label: Bronnen title
    type: textarea
    size: small
  BronnenText:
    label: Bronnen text
    type: textarea
    size: small